use clap::Args;
use iota_types::{STARDUST_PACKAGE_ID, base_types::ObjectID};
use url::Url;

/// Max queue size of checkpoints for the Indexer to process
const DOWNLOAD_QUEUE_SIZE: usize = 200;
/// Limit indexing parallelism on big checkpoints to avoid OOM,
/// by limiting the total size of batch checkpoints to ~20MB
const CHECKPOINT_PROCESSING_BATCH_DATA_LIMIT: u64 = 20000000;

#[derive(Args, Debug, Clone)]
pub struct IndexerConfig {
    /// Option to to synchronize data from a remote Fullnode through REST API
    #[arg(long)]
    pub remote_store_url: Url,
    /// Max queue size of checkpoints for the Indexer to process
    #[arg(long, default_value = DOWNLOAD_QUEUE_SIZE.to_string())]
    #[arg(env = "DOWNLOAD_QUEUE_SIZE")]
    pub download_queue_size: usize,
    /// Limit indexing parallelism on big checkpoints to avoid OOM,
    /// by limiting the total size of batch checkpoints to ~20MB.
    #[arg(long, default_value = CHECKPOINT_PROCESSING_BATCH_DATA_LIMIT.to_string())]
    #[arg(env = "CHECKPOINT_PROCESSING_BATCH_DATA_LIMIT")]
    pub checkpoint_processing_batch_data_limit: usize,
    /// Reset the current database
    #[arg(long)]
    pub reset_db: bool,
    // Instruct the Indexer to store Objects generated by these package IDs
    #[clap(short, long, value_delimiter = ' ', num_args = 1.., default_value = STARDUST_PACKAGE_ID.to_string())]
    pub package_id: ObjectID,
}
