name: Cargo Deny

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: rust-lints-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  bans-licenses-sources:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Run Cargo Deny (bans, licenses, sources)
        run: cargo deny --manifest-path ./Cargo.toml check bans licenses sources

  advisories:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Run Cargo Deny (advisories)
        run: cargo deny --manifest-path ./Cargo.toml check advisories
