name: Publish Docker Images

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and Push Docker Image to iotaledger
    runs-on: ubuntu-latest
    environment: release

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      # Build the Docker image using Docker Compose with no cache
      - name: Build Docker Image
        run: docker compose build --no-cache

      # Tag the Docker image for the registry
      - name: Tag built image
        run: |
          docker tag rebased-stardust-indexer:latest iotaledger/stardust-indexer:latest
          docker tag rebased-stardust-indexer:latest iotaledger/stardust-indexer:${{ github.ref_name }}

      # Push the Docker image to the registry
      - name: Push image
        run: |
          docker push iotaledger/stardust-indexer:latest
          docker push iotaledger/stardust-indexer:${{ github.ref_name }}