name: Publish Docker Images

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and Push Docker Image to IOTA Registry
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to the Docker Registry
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}

      # Build the Docker image using Docker Compose with no cache
      - name: Build Docker Image
        run: docker compose build --no-cache

      # Tag the Docker image for the registry
      - name: Tag Docker Image
        run: |
          docker tag rebased-stardust-indexer:latest docker-registry.iota.org/rebased-stardust-indexer:${{ github.ref_name }}

      # Push the Docker image to the registry
      - name: Push Docker Image
        run: |
          docker push docker-registry.iota.org/rebased-stardust-indexer:${{ github.ref_name }}
